"""Internal native inference-engine contracts and services."""

from mlx_one.engine.block_cache import (
    BlockAllocator,
    BlockId,
    BlockPool,
    BlockRef,
    CacheBlock,
    PageTable,
)
from mlx_one.engine.block_kv import BlockKVCache
from mlx_one.engine.cache import (
    CacheBundle,
    array_nbytes,
    cache_allocated_nbytes,
    cache_capabilities,
    cache_nbytes,
)
from mlx_one.engine.cache_errors import (
    CacheCapacityError,
    CacheCorruptionError,
    CacheError,
    CacheOwnershipError,
    CacheReservationError,
    CacheTopologyUnsupported,
    KVQuantizationUnsupported,
    PrefixReuseUnsupported,
)
from mlx_one.engine.cache_manager import CacheManager
from mlx_one.engine.cache_planner import build_cache_plan
from mlx_one.engine.cache_specs import (
    CacheConfig,
    CacheFingerprint,
    CacheHandle,
    CacheKind,
    CacheMemoryStats,
    CachePlan,
    CacheReservation,
    LayerCacheSpec,
    ReservationState,
)
from mlx_one.engine.contracts import (
    CacheCapabilities,
    EngineError,
    EngineEvent,
    EngineMetrics,
    EngineRequest,
    EngineRuntime,
    ExecutionBatch,
    ModelRunner,
    RequestKind,
    RunnerCapabilities,
    SequenceContext,
    SequenceState,
    TaskRunner,
)
from mlx_one.engine.memory import (
    AdmissionDecision,
    AdmissionStatus,
    MemoryBudget,
    MemoryUsage,
    UnifiedMemoryPlanner,
    forecast_kv_bytes,
)
from mlx_one.engine.prefix_cache import (
    BlockPrefixEntry,
    BlockPrefixIndex,
    BlockPrefixMatch,
    PrefixCache,
    PrefixCacheEntry,
    PrefixCacheKey,
)
from mlx_one.engine.public import Engine, EngineRequestHandle
from mlx_one.engine.runners import ASRRunner, CausalLMRunner, EncoderRunner, VLMRunner
from mlx_one.engine.scheduler import TokenBudgetScheduler

__all__ = [
    "AdmissionDecision",
    "AdmissionStatus",
    "ASRRunner",
    "BlockAllocator",
    "BlockId",
    "BlockKVCache",
    "BlockPool",
    "BlockPrefixEntry",
    "BlockPrefixIndex",
    "BlockPrefixMatch",
    "BlockRef",
    "CacheBlock",
    "CacheBundle",
    "CacheCapacityError",
    "CacheCapabilities",
    "CacheConfig",
    "CacheCorruptionError",
    "CacheError",
    "CacheFingerprint",
    "CacheHandle",
    "CacheKind",
    "CacheManager",
    "CacheMemoryStats",
    "CacheOwnershipError",
    "CachePlan",
    "CacheReservation",
    "CacheReservationError",
    "CacheTopologyUnsupported",
    "CausalLMRunner",
    "EngineError",
    "EngineEvent",
    "EngineMetrics",
    "EngineRequest",
    "Engine",
    "EngineRequestHandle",
    "EngineRuntime",
    "EncoderRunner",
    "ExecutionBatch",
    "KVQuantizationUnsupported",
    "LayerCacheSpec",
    "MemoryBudget",
    "MemoryUsage",
    "ModelRunner",
    "PageTable",
    "PrefixCache",
    "PrefixCacheEntry",
    "PrefixCacheKey",
    "PrefixReuseUnsupported",
    "RequestKind",
    "ReservationState",
    "RunnerCapabilities",
    "SequenceContext",
    "SequenceState",
    "TaskRunner",
    "TokenBudgetScheduler",
    "UnifiedMemoryPlanner",
    "VLMRunner",
    "array_nbytes",
    "build_cache_plan",
    "cache_allocated_nbytes",
    "cache_capabilities",
    "cache_nbytes",
    "forecast_kv_bytes",
]
