"""Public package surface for mlx-one."""

from mlx_one.compat.unsloth import FastLanguageModel
from mlx_one.hardware import (
    HardwareProfileError,
    detect_hardware,
    list_hardware_profiles,
    load_hardware_profile,
)
from mlx_one.inspection import InspectionError, inspect_model
from mlx_one.planning import PlanningError, estimate_memory, plan_inference, plan_training
from mlx_one.schemas import (
    SCHEMA_VERSION,
    ArtifactRef,
    CachePolicy,
    CalibrationRecord,
    CalibrationStatus,
    CapabilityHint,
    CapabilityHintStatus,
    CapabilitySpec,
    CapabilityStatus,
    CheckpointMetadata,
    CompatibilityResult,
    CompatibilityStatus,
    Confidence,
    DatasetFormat,
    DatasetLayout,
    DatasetSpec,
    Failure,
    FitStatus,
    HardwareSpec,
    InspectionResult,
    MemoryEstimate,
    MetricProvenance,
    MetricValue,
    Modality,
    ModelDimensions,
    ModelSource,
    ModelSpec,
    Operation,
    PlanResult,
    Precision,
    ResumeSemantics,
    RunResult,
    RunSpec,
    RunStatus,
    SoftwareProvenance,
    TaskResult,
    TrainConfig,
    TrainingMethod,
    WorkloadKind,
    WorkloadSpec,
)
from mlx_one.training import SFTTrainer

__version__ = "0.1.0a1"

__all__ = [
    "SCHEMA_VERSION",
    "ArtifactRef",
    "CachePolicy",
    "CapabilitySpec",
    "CapabilityStatus",
    "CapabilityHint",
    "CapabilityHintStatus",
    "CalibrationRecord",
    "CalibrationStatus",
    "CompatibilityResult",
    "CompatibilityStatus",
    "CheckpointMetadata",
    "Confidence",
    "Failure",
    "FitStatus",
    "DatasetFormat",
    "DatasetLayout",
    "DatasetSpec",
    "MetricProvenance",
    "MetricValue",
    "HardwareSpec",
    "HardwareProfileError",
    "InspectionError",
    "InspectionResult",
    "MemoryEstimate",
    "Modality",
    "ModelSource",
    "ModelDimensions",
    "ModelSpec",
    "Operation",
    "PlanResult",
    "PlanningError",
    "Precision",
    "ResumeSemantics",
    "RunResult",
    "RunSpec",
    "RunStatus",
    "SoftwareProvenance",
    "TaskResult",
    "TrainingMethod",
    "TrainConfig",
    "FastLanguageModel",
    "SFTTrainer",
    "WorkloadKind",
    "WorkloadSpec",
    "__version__",
    "inspect_model",
    "detect_hardware",
    "estimate_memory",
    "list_hardware_profiles",
    "load_hardware_profile",
    "plan_inference",
    "plan_training",
]
